// <auto-generated />
using System;
using Listo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listo.Api.Migrations
{
    [DbContext(typeof(ListoDbContext))]
    [Migration("20260306234915_UpdateCyclePlanAndTransactionSchema")]
    partial class UpdateCyclePlanAndTransactionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Listo.Api.Models.Account", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("AccountFlag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_flag");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("account_number");

                    b.Property<long>("AccountOwnerSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_owner_sys_id");

                    b.Property<long>("AccountTypeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_type_sys_id");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_due");

                    b.Property<bool>("AutoPay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_pay");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<long?>("DefaultBankAccountSysId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultPaymentMethodSysId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_password");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("ResetAmountDue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("reset_amount_due");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.Property<string>("WebAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("web_address");

                    b.HasKey("SysId");

                    b.HasIndex("AccountOwnerSysId");

                    b.HasIndex("AccountTypeSysId");

                    b.HasIndex("DefaultBankAccountSysId");

                    b.HasIndex("DefaultPaymentMethodSysId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.AccountOwner", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("account_owners", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.AccountType", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("account_types", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.AiPrompt", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Aircraft", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PlaneId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("plane_id");

                    b.HasKey("SysId");

                    b.HasIndex("PlaneId")
                        .IsUnique();

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.BankAccount", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_type");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Color")
                        .HasColumnType("longtext")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("discontinued_date");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_discontinued");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("routing_number");

                    b.HasKey("SysId");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.CycleGoal", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("cycle_goals", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.CyclePlan", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<decimal>("AmountIn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_in");

                    b.Property<decimal>("AmountOut")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_out");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<long>("CycleGoalSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_goal_sys_id");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("discontinued_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_discontinued");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("SysId");

                    b.HasIndex("CycleGoalSysId");

                    b.HasIndex("StartDate");

                    b.ToTable("cycle_plans", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.CycleTransaction", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<long>("CyclePlanSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("cycle_plan_sys_id");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.HasKey("SysId");

                    b.HasIndex("CyclePlanSysId");

                    b.ToTable("cycle_transactions", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Document", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long?>("DocumentTypeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_type_sys_id");

                    b.Property<long?>("EntitySysId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_sys_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mime_type");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("module");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_path");

                    b.Property<long>("UploadedBySysId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("DocumentTypeSysId");

                    b.HasIndex("UploadedBySysId");

                    b.HasIndex("Module", "EntityType", "EntitySysId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.DocumentType", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.LedgerTransaction", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<long>("BankAccountSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("bank_account_sys_id");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<long?>("PaymentSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_sys_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_type");

                    b.HasKey("SysId");

                    b.HasIndex("BankAccountSysId");

                    b.HasIndex("PaymentSysId")
                        .IsUnique();

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Note", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<long>("UserSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("UserSysId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Payment", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<long>("AccountSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_sys_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<long?>("BankAccountSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("bank_account_sys_id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_date");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("confirmation_number");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<long>("PaymentMethodSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_sys_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("SysId");

                    b.HasIndex("AccountSysId");

                    b.HasIndex("BankAccountSysId");

                    b.HasIndex("PaymentMethodSysId");

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.PaymentMethod", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<long>("UsersSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("users_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("UsersSysId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.SavedView", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long>("UserSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_sys_id");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("view_type");

                    b.HasKey("SysId");

                    b.HasIndex("UserSysId", "ViewType", "Name")
                        .IsUnique();

                    b.ToTable("saved_views", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Setting", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value_type");

                    b.HasKey("SysId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.TrainingLog", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<long?>("AircraftSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("aircraft_sys_id");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("HoursFlown")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("hours_flown");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<long>("TrainingTypeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("training_type_sys_id");

                    b.Property<long>("UserSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("AircraftSysId");

                    b.HasIndex("Date");

                    b.HasIndex("TrainingTypeSysId");

                    b.HasIndex("UserSysId");

                    b.ToTable("training_logs", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.TrainingType", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("training_types", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("longtext")
                        .HasColumnName("mfa_secret");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("SysId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Account", b =>
                {
                    b.HasOne("Listo.Api.Models.AccountOwner", "AccountOwner")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountOwnerSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.BankAccount", "DefaultBankAccount")
                        .WithMany()
                        .HasForeignKey("DefaultBankAccountSysId");

                    b.HasOne("Listo.Api.Models.PaymentMethod", "DefaultPaymentMethod")
                        .WithMany()
                        .HasForeignKey("DefaultPaymentMethodSysId");

                    b.Navigation("AccountOwner");

                    b.Navigation("AccountType");

                    b.Navigation("DefaultBankAccount");

                    b.Navigation("DefaultPaymentMethod");
                });

            modelBuilder.Entity("Listo.Api.Models.CyclePlan", b =>
                {
                    b.HasOne("Listo.Api.Models.CycleGoal", "CycleGoal")
                        .WithMany("CyclePlans")
                        .HasForeignKey("CycleGoalSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CycleGoal");
                });

            modelBuilder.Entity("Listo.Api.Models.CycleTransaction", b =>
                {
                    b.HasOne("Listo.Api.Models.CyclePlan", "CyclePlan")
                        .WithMany()
                        .HasForeignKey("CyclePlanSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyclePlan");
                });

            modelBuilder.Entity("Listo.Api.Models.Document", b =>
                {
                    b.HasOne("Listo.Api.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeSysId");

                    b.HasOne("Listo.Api.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedBySysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Listo.Api.Models.LedgerTransaction", b =>
                {
                    b.HasOne("Listo.Api.Models.BankAccount", "BankAccount")
                        .WithMany("LedgerTransactions")
                        .HasForeignKey("BankAccountSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.Payment", "Payment")
                        .WithOne("LedgerTransaction")
                        .HasForeignKey("Listo.Api.Models.LedgerTransaction", "PaymentSysId");

                    b.Navigation("BankAccount");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Listo.Api.Models.Note", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.Payment", b =>
                {
                    b.HasOne("Listo.Api.Models.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountSysId");

                    b.HasOne("Listo.Api.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BankAccount");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsersSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.SavedView", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.TrainingLog", b =>
                {
                    b.HasOne("Listo.Api.Models.Aircraft", "Aircraft")
                        .WithMany("TrainingLogs")
                        .HasForeignKey("AircraftSysId");

                    b.HasOne("Listo.Api.Models.TrainingType", "TrainingType")
                        .WithMany("TrainingLogs")
                        .HasForeignKey("TrainingTypeSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("TrainingType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.Account", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Listo.Api.Models.AccountOwner", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Listo.Api.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Listo.Api.Models.Aircraft", b =>
                {
                    b.Navigation("TrainingLogs");
                });

            modelBuilder.Entity("Listo.Api.Models.BankAccount", b =>
                {
                    b.Navigation("LedgerTransactions");
                });

            modelBuilder.Entity("Listo.Api.Models.CycleGoal", b =>
                {
                    b.Navigation("CyclePlans");
                });

            modelBuilder.Entity("Listo.Api.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Listo.Api.Models.Payment", b =>
                {
                    b.Navigation("LedgerTransaction");
                });

            modelBuilder.Entity("Listo.Api.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Listo.Api.Models.TrainingType", b =>
                {
                    b.Navigation("TrainingLogs");
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
