// <auto-generated />
using System;
using Listo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listo.Api.Migrations
{
    [DbContext(typeof(ListoDbContext))]
    [Migration("20260301054811_AddLksemTables")]
    partial class AddLksemTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Listo.Api.Models.Account", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("AccountFlag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("account_flag");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("account_number");

                    b.Property<long>("AccountOwnerSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_owner_sys_id");

                    b.Property<long>("AccountTypeSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_type_sys_id");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_due");

                    b.Property<bool>("AutoPay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_pay");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_password");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("ResetAmountDue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("reset_amount_due");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.Property<string>("WebAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("web_address");

                    b.HasKey("SysId");

                    b.HasIndex("AccountOwnerSysId");

                    b.HasIndex("AccountTypeSysId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.AccountOwner", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("account_owners", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.AccountType", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SysId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("account_types", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<long>("UsersSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("users_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("UsersSysId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.SavedView", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long>("UserSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_sys_id");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("view_type");

                    b.HasKey("SysId");

                    b.HasIndex("UserSysId", "ViewType", "Name")
                        .IsUnique();

                    b.ToTable("saved_views", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("longtext")
                        .HasColumnName("mfa_secret");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("SysId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.Account", b =>
                {
                    b.HasOne("Listo.Api.Models.AccountOwner", "AccountOwner")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountOwnerSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listo.Api.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountOwner");

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsersSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.SavedView", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.AccountOwner", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Listo.Api.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
