// <auto-generated />
using System;
using Listo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listo.Api.Migrations
{
    [DbContext(typeof(ListoDbContext))]
    partial class ListoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<long>("UsersSysId")
                        .HasColumnType("bigint")
                        .HasColumnName("users_sys_id");

                    b.HasKey("SysId");

                    b.HasIndex("UsersSysId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Property<long>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SysId"));

                    b.Property<DateTime>("CreateTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_timestamp");

                    b.Property<long?>("CreateUser")
                        .HasColumnType("bigint")
                        .HasColumnName("create_user");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("longtext")
                        .HasColumnName("mfa_secret");

                    b.Property<DateTime>("ModifyTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modify_timestamp");

                    b.Property<long?>("ModifyUser")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_user");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("SysId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Listo.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Listo.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsersSysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Listo.Api.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
